[package]
name = "runtime"
description = "Mach-O image loader, dyld fixups and syscall/HLE layer for the Simpsons Arcade iOS emulator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
macho = { path = "../macho" }
guestmem = { path = "../guestmem" }
arm = { path = "../arm" }

[lib]
name = "runtime"
path = "src/lib.rs"
